import js from '@eslint/js';
import typescript from '@typescript-eslint/eslint-plugin';
import typescriptParser from '@typescript-eslint/parser';
import react from 'eslint-plugin-react';
import reactHooks from 'eslint-plugin-react-hooks';
import globals from 'globals';

export default [
  // Global ignores
  {
    ignores: [
      'node_modules/**',
      'dist/**',
      'src-tauri/**',
      '*.config.js',
      '*.config.ts',
      'src/bindings.ts', // Auto-generated by tauri-specta
    ],
  },
  // Base JS config
  js.configs.recommended,
  // TypeScript/React files
  {
    files: ['src/**/*.ts', 'src/**/*.tsx'],
    languageOptions: {
      parser: typescriptParser,
      parserOptions: {
        ecmaVersion: 'latest',
        sourceType: 'module',
        ecmaFeatures: {
          jsx: true,
        },
      },
      globals: {
        ...globals.browser,
        ...globals.es2021,
        React: 'readonly',
        MediaSessionPlaybackState: 'readonly',
        MediaSessionAction: 'readonly',
        MediaSessionActionHandler: 'readonly',
        MediaImage: 'readonly',
        MediaMetadata: 'readonly',
      },
    },
    plugins: {
      '@typescript-eslint': typescript,
      react: react,
      'react-hooks': reactHooks,
    },
    rules: {
      ...typescript.configs.recommended.rules,
      'react/react-in-jsx-scope': 'off',
      'react/prop-types': 'off',
      '@typescript-eslint/no-unused-vars': ['error', { argsIgnorePattern: '^_' }],
      '@typescript-eslint/explicit-function-return-type': 'off',
      '@typescript-eslint/no-explicit-any': 'error',
      'react-hooks/rules-of-hooks': 'error',
      'react-hooks/exhaustive-deps': 'error',
      'no-unused-vars': 'off',
    },
    settings: {
      react: {
        version: 'detect',
      },
    },
  },
  // Test files - allow additional globals
  {
    files: ['src/**/*.test.ts', 'src/**/*.test.tsx', 'src/test/**/*.ts'],
    languageOptions: {
      globals: {
        ...globals.node,
        ...globals.browser,
        ...globals.es2021,
        React: 'readonly',
        vi: 'readonly',
        describe: 'readonly',
        it: 'readonly',
        expect: 'readonly',
        beforeEach: 'readonly',
        afterEach: 'readonly',
        beforeAll: 'readonly',
        afterAll: 'readonly',
        global: 'readonly',
        IntersectionObserverCallback: 'readonly',
      },
    },
  },
  // src-remote: runtime-agnostic mobile bundle — enforce import boundaries
  {
    files: ['src-remote/**/*.{ts,tsx}'],
    languageOptions: {
      parser: typescriptParser,
      parserOptions: {
        ecmaVersion: 'latest',
        sourceType: 'module',
        ecmaFeatures: { jsx: true },
      },
      globals: {
        ...globals.browser,
        ...globals.es2021,
        React: 'readonly',
      },
    },
    rules: {
      // Disabled: src-remote/tsconfig.json enables noUnusedLocals + noUnusedParameters,
      // and @typescript-eslint plugin is not loaded in this block, so the base rule
      // would produce false positives on TypeScript constructs (type imports, interfaces).
      'no-unused-vars': 'off',
      'no-restricted-imports': [
        'error',
        {
          patterns: [
            {
              group: ['@tauri-apps/*', '@tauri-apps/**'],
              message:
                'src-remote is a Tauri-free mobile bundle; do not import Tauri runtime APIs. Use runtime-agnostic code from @/lib or @/components/ui instead.',
            },
            {
              group: ['zustand', 'zustand/**'],
              message:
                'src-remote is a Tauri-free mobile bundle; do not use Zustand. Receive state via the WebSocket protocol (RemoteState) and use local React state instead.',
            },
            {
              group: ['@tanstack/*', '@tanstack/**'],
              message:
                'src-remote is a Tauri-free mobile bundle; do not use @tanstack/react-query or react-virtual. Use fetch() and local React state instead.',
            },
            {
              group: ['@/features/*', '@/features/**'],
              message:
                'src-remote may not import desktop feature modules from @/features — they carry Tauri and Zustand dependencies. Import runtime-agnostic code from @/lib or @/components/ui instead.',
            },
            {
              group: ['@/hooks/*', '@/hooks/**'],
              message:
                'src-remote may not import desktop hooks from @/hooks — they are tied to Tauri or Zustand stores. Implement mobile-specific hooks inside src-remote/ instead.',
            },
            {
              group: ['@/lib/logger', '@/lib/tauri'],
              message:
                'src-remote is a Tauri-free mobile bundle; @/lib/logger and @/lib/tauri are Tauri-coupled. Use src-remote-local utilities instead.',
            },
            {
              group: ['@/bindings', '@/bindings/**'],
              message:
                'src-remote is a Tauri-free mobile bundle; @/bindings is auto-generated from Tauri IPC commands and must not be imported here.',
            },
            {
              group: ['@/**/store', '@/**/store.ts'],
              message:
                'src-remote must not import desktop Zustand stores. Receive application state via the WebSocket protocol (RemoteState) instead.',
            },
          ],
        },
      ],
    },
  },
];
