// @ts-nocheck
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
/**
 * Scans browser cookies for a SoundCloud oauth_token, verifies it
 * against the API, and caches the result. Emits an auth state event.
 * 
 * # Returns
 * * `Ok(true)` - A valid token was found and verified
 * * `Ok(false)` - No valid token found (not signed in)
 * * `Err(String)` - Error during the check
 */
async checkAuth() : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("check_auth") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Re-verifies auth on demand (e.g., after download 401/403).
 * First tries to re-verify the cached token (cheap API call) before
 * falling back to a full browser cookie scan (expensive I/O).
 * If no valid token is found, emits `auth-reauth-needed` so the frontend can prompt the user.
 */
async refreshAuth() : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("refresh_auth") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Signs out by clearing cached auth state and emitting signed-out event.
 * 
 * Note: This does NOT delete the browser cookie — the user remains logged in
 * to SoundCloud in their browser. It only clears the app's cached token.
 */
async signOut() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("sign_out") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async validateSoundcloudUrl(url: string) : Promise<ValidationResult> {
    return await TAURI_INVOKE("validate_soundcloud_url", { url });
},
async getPlaylistInfo(url: string) : Promise<Result<PlaylistInfo, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_playlist_info", { url }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getTrackInfo(url: string) : Promise<Result<TrackInfo, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_track_info", { url }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Test the FFmpeg sidecar by getting its version.
 * 
 * This command verifies that the FFmpeg binary is properly bundled
 * and can be executed as a Tauri sidecar.
 */
async testFfmpeg() : Promise<Result<string, ErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("test_ffmpeg") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Download and convert a track to MP3 with metadata embedding.
 * 
 * This command orchestrates the full download pipeline:
 * 1. Resolves stream URL via SoundCloud API v2
 * 2. Downloads and converts to 320kbps MP3 via ffmpeg
 * 3. Embeds ID3 metadata (title, artist, album, track number, artwork)
 * 4. Emits progress events throughout the process
 */
async downloadTrackFull(request: DownloadRequest) : Promise<Result<string, ErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("download_track_full", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Start processing a download queue.
 * 
 * This command accepts a list of tracks and processes them sequentially.
 * Progress events are emitted via:
 * - `queue-progress`: Overall queue progress (X of Y)
 * - `download-progress`: Per-track status
 * - `queue-complete`: Final results when queue finishes
 * - `queue-cancelled`: When queue is cancelled by user
 */
async startDownloadQueue(request: StartQueueRequest) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_download_queue", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Cancel the current download queue.
 */
async cancelDownloadQueue() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cancel_download_queue") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Respond to an auth choice prompt during download.
 */
async respondToAuthChoice(choice: AuthChoice) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("respond_to_auth_choice", { choice }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Respond to a rate limit choice prompt during download.
 */
async respondToRateLimitChoice(choice: RateLimitChoice) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("respond_to_rate_limit_choice", { choice }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async checkWritePermission(path: string) : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("check_write_permission", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getDefaultDownloadPath() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_default_download_path") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async validateDownloadPath(path: string) : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("validate_download_path", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Checks for available updates silently.
 * 
 * Network errors and timeouts are handled gracefully — the app continues
 * normally without showing errors to the user (FR27 compliance).
 * 
 * # Returns
 * * `Ok(Some(UpdateInfo))` - Update available with version, notes, and date
 * * `Ok(None)` - No update available, or check failed silently
 */
async checkForUpdates() : Promise<Result<UpdateInfo | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("check_for_updates") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Downloads and installs an available update.
 * 
 * This will download the update in the background and install it.
 * On most platforms, the app will need to restart to apply the update.
 * 
 * # Returns
 * * `Ok(())` - Update downloaded and installed successfully
 * * `Err(String)` - Error message if installation fails
 */
async installUpdate() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("install_update") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getLibraryPlaylists() : Promise<Result<LibraryPlaylist[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_library_playlists") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async resolveLibraryArtwork(playlistId: number, secretToken: string | null) : Promise<Result<string | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("resolve_library_artwork", { playlistId, secretToken }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async clearLibraryCache() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("clear_library_cache") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getLibraryPlaylistTracks(playlistId: number) : Promise<Result<TrackInfo[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_library_playlist_tracks", { playlistId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Scan the output directory for tracks already downloaded (by SoundCloud track ID in ID3 metadata).
 * 
 * Returns the list of track IDs that already exist in the output directory.
 */
async scanExistingTracks(outputDir: string, trackIds: string[]) : Promise<string[]> {
    return await TAURI_INVOKE("scan_existing_tracks", { outputDir, trackIds });
},
async searchTracks(query: string, limit: number, offset: number) : Promise<Result<SearchResponse, ErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("search_tracks", { query, limit, offset }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async playerPlayAt(queue: PlaybackItem[], index: number) : Promise<Result<null, ErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("player_play_at", { queue, index }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async playerPause() : Promise<Result<null, ErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("player_pause") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async playerResume() : Promise<Result<null, ErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("player_resume") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async playerSeek(positionMs: number) : Promise<Result<null, ErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("player_seek", { positionMs }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async playerSetVolume(volume: number) : Promise<Result<null, ErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("player_set_volume", { volume }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async playerNext() : Promise<Result<null, ErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("player_next") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async playerPrevious() : Promise<Result<null, ErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("player_previous") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async playerStop() : Promise<Result<null, ErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("player_stop") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async playerGetState() : Promise<Result<PlayerStateSnapshot, ErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("player_get_state") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async playerReorderQueue(fromIndex: number, toIndex: number) : Promise<Result<null, ErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("player_reorder_queue", { fromIndex, toIndex }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async playerRemoveFromQueue(index: number) : Promise<Result<null, ErrorResponse>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("player_remove_from_queue", { index }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type AuthChoice = "re_authenticated" | "continue_standard"
export type DownloadRequest = { trackUrl: string; trackId: string; title: string; artist: string; album: string | null; trackNumber: number | null; totalTracks: number | null; artworkUrl: string | null; outputDir: string | null; durationMs: number }
export type ErrorResponse = { code: string; message: string }
export type LibraryPlaylist = { id: number; title: string; username: string; artwork_url: string | null; track_count: number; duration: number; permalink_url: string; is_owned: boolean; is_public: boolean; secret_token: string | null }
/**
 * A track in the playback queue.
 */
export type PlaybackItem = { track_id: number; track_url: string; title: string; artist: string; artwork_url: string | null; duration_ms: number }
/**
 * Playback state enum.
 */
export type PlaybackState = "stopped" | "loading" | "playing" | "paused"
/**
 * Full state snapshot returned by `player_get_state`.
 */
export type PlayerStateSnapshot = { state: PlaybackState; current_track: PlaybackItem | null; queue: PlaybackItem[]; cursor: number; position_ms: number; duration_ms: number; volume: number }
/**
 * Playlist information from SoundCloud API.
 */
export type PlaylistInfo = { id: number; title: string; user: UserInfo; artwork_url: string | null; track_count: number; tracks: TrackInfo[] }
export type QueueItemRequest = { trackUrl: string; trackId: string; title: string; artist: string; artworkUrl: string | null; durationMs: number }
export type RateLimitChoice = "retry" | "stop"
export type SearchResponse = { collection: TrackInfo[]; total_results: number | null }
export type StartQueueRequest = { tracks: QueueItemRequest[]; albumName: string | null; outputDir: string | null; maxConcurrent: number | null; preserveOrder: boolean | null }
/**
 * Track information from SoundCloud API.
 */
export type TrackInfo = { id: number; title: string; user: UserInfo; artwork_url: string | null; 
/**
 * Duration in milliseconds.
 */
duration: number; permalink_url: string }
/**
 * Information about an available update.
 */
export type UpdateInfo = { version: string; body: string | null; date: string | null }
export type UrlType = "playlist" | "track"
export type UserInfo = { username: string; avatar_url: string | null }
export type ValidationError = { code: string; message: string; hint: string | null }
export type ValidationResult = { valid: boolean; urlType: UrlType | null; error: ValidationError | null }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
